spring:
  profiles:
    active: prod
  main:
    web-application-type: reactive
  webflux:
    base-path: /es
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  r2dbc:
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1

server:
  port: 8080

iot:
  mqtt:
    qos: 1
    auto-reconnect: true
    up-topic: /home_data/device/+/up/report
    dn-topic: /home_data/device/%s/dn/ctr
    timeout: 5000
  storage:
    location: ./storage/
  device:
    heartbeat-timeout: 300000 # = 5 * 60 * 1000

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iot?useSSL=false
    username: root
    password: Icom@2023
iot:
  mqtt:
    url: tcp://localhost:22283
    username: iot
    password: 1
    pub-client-id: java-server-publisher
    sub-client-id: java-server-subscriber

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: 1
iot:
  mqtt:
    url: tcp://broker.hivemq.com:1883
    username: test123
    password: 1
    pub-client-id:
    sub-client-id:
